version: '3'

services:
  django:
    build: .
    container_name: django-con
    command: python manage.py runserver 0.0.0.0:8090
    volumes:
      - .:/usr/src/app
    ports:
      - "8090:8090"
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: pgdb_con

volumes:
  pgdbdata: null



