version: '3.1'

services:
  php-env:
    build: .
    links:
      - db
    volumes:
      - ./src/:/var/www/html
    ports:
      - 8010:80
  db:
    image: mariadb:10.6
    restart: always
    volumes: 
      - ./mysql/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: EmPelmeny123

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1